genes <- c("BRCA1", "TP53", "EGFR")
expression <- c(12.5, 45.2, 30.1)
condition <- c("Control", "Treatment", "Treatment")
exp_data <- data.frame(Genes=genes, Expression=expression, Condition=condition)
str(exp_data)
png("~/bioinformatics_hw/r_task/expression_plot.png")
barplot(exp_data$Expression, names.arg=exp_data$Genes)
dev.off()
